name = "transparent-mac"
account_id = "2ccb840de076261467812cbc32f8aa47"
workers_dev = false
compatibility_date = "2025-05-05"
main = "worker/index.ts"

durable_objects.bindings = [
    { name = "ETHERNET_ZONE", class_name = "EthernetZone" },
]
kv_namespaces = [
    { binding = "VARZ", id = "1725dc172d284ec4bd41bf950d5df01c", preview_id = "535cb0b90b1a44f1b284919f2751aedb" },
]

[[migrations]]
tag = "v1"
new_classes = ["EthernetZone"]

[assets]
directory = "./build"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[env.production]
routes = [
    { pattern = "system6.app/*", zone_name = "system6.app" },
    { pattern = "*.system6.app/*", zone_name = "system6.app" },
    { pattern = "system7.app/*", zone_name = "system7.app" },
    { pattern = "*.system7.app/*", zone_name = "system7.app" },
    { pattern = "macos8.app/*", zone_name = "macos8.app" },
    { pattern = "*.macos8.app/*", zone_name = "macos8.app" },
    { pattern = "macos9.app/*", zone_name = "macos9.app" },
    { pattern = "*.macos9.app/*", zone_name = "macos9.app" },
    { pattern = "kanjitalk7.app/*", zone_name = "kanjitalk7.app" },
    { pattern = "*.kanjitalk7.app/*", zone_name = "kanjitalk7.app" },
    { pattern = "infinitemac.org/*", zone_name = "infinitemac.org" },
    { pattern = "*.infinitemac.org/*", zone_name = "infinitemac.org" },
    { pattern = "mac.persistent.info/*", zone_name = "persistent.info" },
]
durable_objects.bindings = [
    { name = "ETHERNET_ZONE", class_name = "EthernetZone" },
]
kv_namespaces = [{ binding = "VARZ", id = "1725dc172d284ec4bd41bf950d5df01c" }]

r2_buckets = [{ binding = "DISK_BUCKET", bucket_name = "infinite-mac-disk" }]

[observability]
enabled = true
head_sampling_rate = 0.1
